### ISSUE TITLE
How to add integrate with react-imask

### ISSUE THREAD

**Issue by pawelmidur** [dohomi/react-hook-form-mui#166]
How to add integration with react-imask? Is it possible?

[MUI DOC - Integration with 3rd party input libraries](https://mui.com/material-ui/react-text-field/#integration-with-3rd-party-input-libraries)

**Comment by dohomi** [comment]
Did you try passing the props as recommended? You can also provide a component prop to overwrite the default component.

**Comment by pawelmidur** [comment]
Yes I did, but I have 2 errors:
```
client.js:1 Warning: You provided a `value` prop to a form field without an `onChange` handler. This will render a read-only field. If the field should be mutable use `defaultValue`. Otherwise, set either `onChange` or `readOnly`.
    at input
    at eval (webpack-internal:///./node_modules/react-imask/esm/input.js:16:5)
    at MaskedComponent (webpack-internal:///./node_modules/react-imask/esm/mixin.js:69:7)
    at IMaskInputFn
    at TextMaskCustom (webpack-internal:///./components/controllers/MaskInputController.tsx:48:13)
```
and
```
lost focus on input after write one char, when hiding error helper text
```

I cant make example on "codesandbox", becouse sandbox have 6.2.0 version only.

```
import { forwardRef } from 'react';
import { FieldValues, TextFieldElement, TextFieldElementProps } from 'react-hook-form-mui';
import { IMaskInput } from 'react-imask';
import { TextField } from '@mui/material';

import { controllersValidator } from 'lib/controllersValidator';

const MaskInputController = <T extends FieldValues = FieldValues>(
  props: TextFieldElementProps<T> & { mask: string },
): JSX.Element => {
  const { mask, ...rest } = props;

  return (
    <TextFieldElement
      {...rest}
      validation={controllersValidator({ ...rest })}
      component={(componentProps) => (
        <TextField
          {...componentProps}
          InputLabelProps={{
            ...componentProps.InputLabelProps,
            shrink: true,
          }}
          InputProps={{
            ...componentProps.InputProps,
            inputComponent: TextMask as any,
          }}
          inputProps={{
            ...componentProps.inputProps,
            mask: mask,
          }}
        />
      )}
    />
  );
};

export default MaskInputController;

interface TextMaskProps {
  onChange: (event: { target: { name: string; value: string } }) => void;
  name: string;
  mask: string;
}

const TextMask = forwardRef<HTMLInputElement, TextMaskProps>(function TextMaskCustom(props, ref) {
  const { mask, onChange, ...other } = props;
  return (
    <IMaskInput
      {...other}
      mask={mask}
      overwrite
      lazy={false}
      placeholderChar={'_'}
      inputRef={ref}
      onAccept={(_value: string, maskValue: { _unmaskedValue: string; _value: string }) => {
        onChange({ target: { name: props.name, value: maskValue._unmaskedValue } });
      }}
    />
  );
});
```
