### ISSUE TITLE
Does this library support Nextjs 15 with React 19rc already?

### ISSUE THREAD

**Issue by tstiemerling** [dohomi/react-hook-form-mui#331]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

Just updated to Nextjs 15 (with React 19rc), and am seeing a lot of the following errors:

Cannot update a component (`MyComponent`) while rendering a different component (`TextFieldElement`). To locate the bad setState() call inside `TextFieldElement`.

Stack trace for one of them seems to point to this library (but could be red herring):

Component Stack
    at _c (CheckboxElement.tsx:130:49)
    at div (<anonymous>)
    at MuiGrid2-root (node_modules\@emotion\react\dist\emotion-element-7a1343fa.browser.development.esm.js:48:27)
    at Grid (Cnode_modules\@mui\material\node_modules\@mui\system\esm\Grid\createGrid.js:74:27)
    at div (<anonymous>)
    at MuiGrid2-root (node_modules\@emotion\react\dist\emotion-element-7a1343fa.browser.development.esm.js:48:27)
    at Grid (node_modules\@mui\material\node_modules\@mui\system\esm\Grid\createGrid.js:74:27)
    at LocalizationProvider (node_modules\@mui\x-date-pickers\LocalizationProvider\LocalizationProvider.js:28:19)
    at form (<anonymous>)
    at FormProvider (node_modules\react-hook-form\dist\index.esm.mjs:196:13)
...

### Expected behavior 🤔

No errors

### Steps to reproduce 🕹

Steps:

1.
2.
3.
4.

**Comment by youyoumu** [comment]
https://github.com/dohomi/react-hook-form-mui/blob/1b256b26edc27036474e68494a443d6afa1884d0/packages/rhf-mui/package.json#L50

can we get react 19 support?

**Comment by dohomi** [comment]
this is supported in latest versions.
