### ISSUE TITLE
Storybook is not working anymore since 3.5.0

### ISSUE THREAD

**Issue by TomFreudenberg** [dohomi/react-hook-form-mui#40]
Hi @dohomi 

your latest release 3.5.0 does break building our storybook. Using 3.4.0 all is working as expected.

This is the error log:

```
info @storybook/react v6.4.22
info 
info => Loading presets
info => Serving static files from ././public at /
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
10% building 0/1 entries 0/0 dependencies 0/0 modules
info => Cleared cached manager config
<i> [webpack-dev-middleware] wait until bundle finished
17% building 2/16 entries 5400/5716 dependencies 664/1715 modulesassets by chunk 4.31 MiB (id hint: vendors)
  assets by status 3.95 MiB [big]
    asset vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-7c62db.manager.bundle.js 3.59 MiB [emitted] [big] (id hint: vendors)
    asset vendors-node_modules_storybook_components_dist_modern_ScrollArea_OverlayScrollbars_js.manager.bundle.js 366 KiB [emitted] [big] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_modern_syntaxhighlighter_syntaxhighlighter_js.manager.bundle.js 190 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_modern_tooltip_WithTooltip_js.manager.bundle.js 108 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_modern_controls_Color_js.manager.bundle.js 61.9 KiB [emitted] (id hint: vendors)
  asset vendors-node_modules_storybook_components_dist_modern_ScrollArea_GlobalScrollAreaStyles_js.manager.bundle.js 13.6 KiB [emitted] (id hint: vendors)
asset runtime~main.manager.bundle.js 14.2 KiB [emitted] (name: runtime~main)
asset index.html 3.03 KiB [emitted]
asset main.manager.bundle.js 1.52 KiB [emitted] (name: main)
asset node_modules_unfetch_dist_unfetch_js.manager.bundle.js 1.27 KiB [emitted]
Entrypoint main [big] 3.61 MiB = runtime~main.manager.bundle.js 14.2 KiB vendors-node_modules_storybook_addon-actions_dist_esm_register_js-node_modules_storybook_addo-7c62db.manager.bundle.js 3.59 MiB main.manager.bundle.js 1.52 KiB
orphan modules 1.34 MiB [orphan] 346 modules
runtime modules 8.71 KiB 15 modules
javascript modules 3.88 MiB 711 modules
json modules 1.52 KiB
  ./node_modules/character-entities-legacy/index.json 1.24 KiB [built] [code generated]
  ./node_modules/character-reference-invalid/index.json 289 bytes [built] [code generated]
manager (webpack 5.72.1) compiled successfully in 7354 ms
99% done plugins webpack-hot-middlewarewebpack built preview 9d0b181ee24f6071c08e in 13884ms
ModuleNotFoundError: Module not found: Error: Can't resolve '@mui/icons-material/Cancel' in '/Workspace/node_modules/react-hook-form-mui/dist'
Did you mean 'Cancel.js'?
BREAKING CHANGE: The request '@mui/icons-material/Cancel' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Workspace/node_modules/webpack/lib/Compilation.js:2016:28
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Workspace/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Workspace/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Workspace/node_modules/neo-async/async.js:6883:13
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:892:17
    at finishResolved (/Workspace/node_modules/enhanced-resolve/lib/Resolver.js:294:11)
    at /Workspace/node_modules/enhanced-resolve/lib/Resolver.js:362:25
    at /Workspace/node_modules/enhanced-resolve/lib/Resolver.js:434:24
    at eval (eval at create (/Workspace/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve '@mui/icons-material/Cancel' in '/Workspace/node_modules/react-hook-form-mui/dist'
  Parsed request is a module
  using description file: /Workspace/node_modules/react-hook-form-mui/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Workspace/node_modules/react-hook-form-mui/dist/node_modules doesn't exist or is not a directory
      /Workspace/node_modules/react-hook-form-mui/node_modules doesn't exist or is not a directory
      /Workspace/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Workspace/node_modules
        existing directory /Workspace/node_modules/@mui/icons-material
          using description file: /Workspace/node_modules/@mui/icons-material/package.json (relative path: .)
            using description file: /Workspace/node_modules/@mui/icons-material/package.json (relative path: ./Cancel)
              Field 'browser' doesn't contain a valid alias configuration
              /Workspace/node_modules/@mui/icons-material/Cancel doesn't exist
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '@mui/icons-material/Visibility' in '/Workspace/node_modules/react-hook-form-mui/dist'
Did you mean 'Visibility.js'?
BREAKING CHANGE: The request '@mui/icons-material/Visibility' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Workspace/node_modules/webpack/lib/Compilation.js:2016:28
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Workspace/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Workspace/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Workspace/node_modules/neo-async/async.js:6883:13
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:892:17
    at finishResolved (/Workspace/node_modules/enhanced-resolve/lib/Resolver.js:294:11)
    at /Workspace/node_modules/enhanced-resolve/lib/Resolver.js:362:25
    at /Workspace/node_modules/enhanced-resolve/lib/Resolver.js:434:24
    at eval (eval at create (/Workspace/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve '@mui/icons-material/Visibility' in '/Workspace/node_modules/react-hook-form-mui/dist'
  Parsed request is a module
  using description file: /Workspace/node_modules/react-hook-form-mui/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Workspace/node_modules/react-hook-form-mui/dist/node_modules doesn't exist or is not a directory
      /Workspace/node_modules/react-hook-form-mui/node_modules doesn't exist or is not a directory
      /Workspace/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Workspace/node_modules
        existing directory /Workspace/node_modules/@mui/icons-material
          using description file: /Workspace/node_modules/@mui/icons-material/package.json (relative path: .)
            using description file: /Workspace/node_modules/@mui/icons-material/package.json (relative path: ./Visibility)
              Field 'browser' doesn't contain a valid alias configuration
              /Workspace/node_modules/@mui/icons-material/Visibility doesn't exist
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
ModuleNotFoundError: Module not found: Error: Can't resolve '@mui/icons-material/VisibilityOff' in '/Workspace/node_modules/react-hook-form-mui/dist'
Did you mean 'VisibilityOff.js'?
BREAKING CHANGE: The request '@mui/icons-material/VisibilityOff' failed to resolve only because it was resolved as fully specified
(probably because the origin is strict EcmaScript Module, e. g. a module with javascript mimetype, a '*.mjs' file, or a '*.js' file where the package.json contains '"type": "module"').
The extension in the request is mandatory for it to be fully specified.
Add the extension to the request.
    at /Workspace/node_modules/webpack/lib/Compilation.js:2016:28
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:798:13
    at eval (eval at create (/Workspace/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:270:22
    at eval (eval at create (/Workspace/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:434:22
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:116:11
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:670:25
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:855:8
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:975:5
    at /Workspace/node_modules/neo-async/async.js:6883:13
    at /Workspace/node_modules/webpack/lib/NormalModuleFactory.js:892:17
    at finishResolved (/Workspace/node_modules/enhanced-resolve/lib/Resolver.js:294:11)
    at /Workspace/node_modules/enhanced-resolve/lib/Resolver.js:362:25
    at /Workspace/node_modules/enhanced-resolve/lib/Resolver.js:434:24
    at eval (eval at create (/Workspace/node_modules/enhanced-resolve/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
resolve '@mui/icons-material/VisibilityOff' in '/Workspace/node_modules/react-hook-form-mui/dist'
  Parsed request is a module
  using description file: /Workspace/node_modules/react-hook-form-mui/package.json (relative path: ./dist)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Workspace/node_modules/react-hook-form-mui/dist/node_modules doesn't exist or is not a directory
      /Workspace/node_modules/react-hook-form-mui/node_modules doesn't exist or is not a directory
      /Workspace/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Workspace/node_modules
        existing directory /Workspace/node_modules/@mui/icons-material
          using description file: /Workspace/node_modules/@mui/icons-material/package.json (relative path: .)
            using description file: /Workspace/node_modules/@mui/icons-material/package.json (relative path: ./VisibilityOff)
              Field 'browser' doesn't contain a valid alias configuration
              /Workspace/node_modules/@mui/icons-material/VisibilityOff doesn't exist
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

This is my package.json

```json
  "dependencies": {
    "@emotion/cache": "11.7.1",
    "@emotion/react": "11.9.0",
    "@emotion/server": "11.4.0",
    "@emotion/styled": "11.8.1",
    "@fontsource/roboto": "4.5.7",
    "@hookform/resolvers": "2.8.10",
    "@mui/icons-material": "5.8.0",
    "@mui/lab": "5.0.0-alpha.82",
    "@mui/material": "5.8.0",
    "commander": "9.2.0",
    "date-fns": "2.28.0",
    "deepmerge": "4.2.2",
    "dotenv-cli": "5.1.0",
    "import-jsx": "4.0.1",
    "ink": "3.2.0",
    "next": "12.1.6",
    "next-auth": "4.3.4",
    "node-cache": "5.1.2",
    "nodemailer": "6.7.5",
    "prop-types": "15.8.1",
    "react": "17.0.2 && <18",
    "react-dom": "17.0.2 && <18",
    "react-hook-form": "7.31.1",
    "react-hook-form-mui": "3.5.0",
    "react-tracked": "1.7.9",
    "vest": "4.4.0"
  },
  "devDependencies": {
    "@babel/core": "7.17.12",
    "@storybook/addon-actions": "6.4.22",
    "@storybook/addon-controls": "6.4.22",
    "@storybook/addon-docs": "6.4.22",
    "@storybook/addon-essentials": "6.4.22",
    "@storybook/addon-interactions": "6.4.22",
    "@storybook/addon-links": "6.4.22",
    "@storybook/builder-webpack5": "6.4.22",
    "@storybook/manager-webpack5": "6.4.22",
    "@storybook/preset-scss": "1.0.3",
    "@storybook/react": "6.4.22",
    "@storybook/testing-library": "0.0.11",
    "@testing-library/jest-dom": "5.16.4",
    "@testing-library/react": "12.1.4 && <13",
    "@testing-library/user-event": "14.2.0",
    "@types/jest": "27.5.1",
    "@types/node": "17.0.34",
    "@types/react": "17.0.43 && <18",
    "@typescript-eslint/eslint-plugin": "5.25.0",
    "@typescript-eslint/parser": "5.25.0",
    "@typescript-eslint/typescript-estree": "5.25.0",
    "babel-jest": "28.1.0",
    "babel-loader": "8.2.5",
    "css-loader": "6.7.1",
    "docsify-cli": "4.4.4",
    "eslint": "8.15.0",
    "eslint-config-airbnb": "19.0.4",
    "eslint-config-next": "12.1.6",
    "eslint-config-prettier": "8.5.0",
    "eslint-plugin-import": "2.26.0",
    "eslint-plugin-mui-unused-classes": "github:4commerce-technologies-AG/eslint-plugin-material-ui-unused-classes",
    "eslint-plugin-prettier": "4.0.0",
    "eslint-plugin-storybook": "0.5.12",
    "identity-obj-proxy": "3.0.0",
    "jest": "28.1.0",
    "jest-environment-jsdom": "28.1.0",
    "jest-transform-yaml": "1.0.0",
    "jest-watch-typeahead": "1.1.0",
    "js-yaml": "4.1.0",
    "jsdoc-babel": "0.5.0",
    "jsdoc-to-markdown": "7.1.1",
    "next-multilingual-alternate": "github:4commerce-technologies-AG/next-multilingual-alternate#0.10.3-stable",
    "prettier": "2.6.2",
    "react-test-renderer": "17.0.2 && <18",
    "sass": "1.51.0",
    "sass-loader": "12.6.0",
    "storybook-addon-next-router": "3.1.1",
    "style-loader": "3.3.1",
    "typescript": "4.6.4",
    "yaml-loader": "0.8.0"
  }
```

I am using 3.4.0 instead currently again to continue our development

**Comment by dohomi** [comment]
@TomFreudenberg I swop `microbundle` for `tsup` in hope of having faster deploys and more fun while coding. But I will revert the changes for now and see if that fixes the issue. I would still like to investigate what is going wrong with using `tsup`

**Comment by TomFreudenberg** [comment]
For sure - as I can help let me know

**Comment by dohomi** [comment]
@TomFreudenberg I just updated 3.5.1 - its still with `tsup` I am just curious if it works now?

**Comment by TomFreudenberg** [comment]
@dohomi Dominic, I am sorry but error stil the same issue with 3.5.1

You may signal me and I use master branch - so you don't need to update the release always

**Comment by dohomi** [comment]
Can you make sure that all `peerDependenyies` are set? 
```
Can't resolve '@mui/icons-material/Visibility'
```
This might mean that `npm i @mui/icons-material` is missing?

**Comment by dohomi** [comment]
@TomFreudenberg can you try 3.5.2? I changed the tsup command to legacy, in my own project its working now.

**Comment by dohomi** [comment]
awesome!
